######################################################################
# Automatically generated by qmake (2.01a) Thu Aug 28 11:23:09 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += Init.cpp
