######################################################################
# Automatically generated by qmake (3.0) Wed Jun 4 17:42:43 2014
######################################################################

TEMPLATE = app
TARGET = Input_Widget
INCLUDEPATH += .

# Input
HEADERS += Init.h
SOURCES += Init.cpp

QT += widgets
